FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt /app
RUN pip3 install -r /app/requirements.txt --no-cache-dir
COPY ./infra_pytest/wait-for-it.sh ./
RUN chmod +x wait-for-it.sh
COPY . ./

CMD ["python3", "-m", "pytest", "tests/", "-v"]