version: '3.8'
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
  monitoring:
    build:
      context: ../
      dockerfile: Dockerfile-pytest
    command: ["./wait-for-it.sh", "db:5432", "--timeout=3", "--strict", "--", "python", "-m", "pytest", "tests/", "-v"]
    depends_on:
      - db
    env_file:
      - ../.env